apiVersion: apps/v1
kind: Deployment
metadata:
  name: sb-ce-youtube-deployment-dev
  labels:
    app: sb-ce-youtube-dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sb-ce-youtube-dev
  template:
    metadata:
      labels:
        app: sb-ce-youtube-dev
    spec:
      containers:
        - name: sb-ce-youtube-dev
          imagePullPolicy: Always
          image: 003718499156.dkr.ecr.us-east-1.amazonaws.com/sb-ce-youtube:dev
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: sb-ce-youtube-service-dev
spec:
  selector:
    app: sb-ce-youtube-dev
  type: ClusterIP
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080